create database project_2

use project_2

SELECT @@SERVERNAME AS ServerName;

USE project_2;
SELECT TOP 5 * FROM customer_shopping_behavior;


-- Q1. What is the total revenue generated by male vs. female customers ?!
select gender, sum(purchase_amount) as revenue from customer_shopping_behavior
group by gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer_shopping_behavior
where discount_applied = 'yes' and purchase_amount>=(select AVG(purchase_amount) from customer_shopping_behavior)

-- 03. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,ROUND(AVG(review_rating), 2) as [Average Product Rating] from customer_shopping_behavior
group by item_purchased
order by AVG(review_rating) desc

-- 04. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,AVG(purchase_amount) from customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribes
select subscription_status,COUNT(customer_id)[total_customer],AVG(purchase_amount)[avg_spend],
sum(purchase_amount)[total_revenue] from customer_shopping_behavior
group by subscription_status
order by total_revenue,avg_spend

-- 06. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,ROUND(100*SUM(CASE When discount_applied = 'yes' then 1 else 0 end)/COUNT(*),2) as [discount Rate] from customer_shopping_behavior
group by item_purchased
order by [discount Rate] desc


-- Q7. Segment customers into New, Returning, and Loyal based on their total -- number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS [customer_segment]
    FROM customer_shopping_behavior
)
SELECT 
    customer_segment, 
    COUNT(*) AS [No. of Customers]
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT 
    category, 
    item_purchased, 
    total_purchases
FROM ranked_products
WHERE rnk <= 3
ORDER BY category, total_purchases DESC;


-- Q9. Are customers who are repeat buyers (more than S previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as [repeat_buyers]
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status 


-- Q10. What is the revenue contribution of each age group ?!
select age_group,
SUM (purchase_amount) as total_revenue
from customer_shopping_behavior
group by age_group
order by total_revenue desc;